### PR TITLE
removing purchase model

### PR DESCRIPTION
**Pull request by nnarayen**

### CODE REVIEW

**Comment by varunrau** [comment]
@nnarayen merge conflicts :(

**Comment by varunrau** [comment]
@nnarayen is this ready?

**Comment by varunrau** [comment]
oh wait nvm the flags are still there for public lists

**Comment by nnarayen** [comment]
if everything looks good to you it should be ready. I saw a comment that the flags are still there for public lists but I removed that with the most recent commit?

**Comment by varunrau** [comment]
LGTM!

**Pull request merged**
